export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const TOGGLE_EMAIL_VERIFICATION_MODAL = 'TOGGLE_EMAIL_VERIFICATION_MODAL';
export const REQUEST_VEREIFICATION_CODE = 'REQUEST_VEREIFICATION_CODE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_ALERT = 'GET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

export const OPEN_CONFIRM = 'OPEN_CONFIRM';
export const CLOSE_CONFIRM = 'CLOSE_CONFIRM';
export const SET_CONFIRM = 'SET_CONFIRM';

export const GET_TRANSACTIONS = 'GET_TRANSACTIONS';
export const CHANGE_CURR_MONTH = 'CHANGE_CURR_MONTH';
export const GET_TRANSACTION = 'GET_TRANSACTION';
export const CLOSE_TRANSACTION_DETAILS = 'CLOSE_TRANSACTION_DETAILS';
export const CREATE_TRANSACTION = 'CREATE_TRANSACTION';
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const UNLOAD_TRANSACTIONS = 'UNLOAD_TRANSACTIONS';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const CLOSE_CATEGORY_DETAILS = 'CLOSE_CATEGORY_DETAILS';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UNLOAD_CATEGORIES = 'UNLOAD_CATEGORIES';